_help_parse: Options affecting listfile parsing
parse:
  _help_additional_commands:
  - Specify structure for custom cmake functions
  additional_commands:
    catch_discover_tests:
      pargs:
        nargs: '*'
        flags: []
      kwargs:
        OUTPUT_DIR: 1
        OUTPUT_PREFIX: 1
        OUTPUT_SUFFIX: 1
        REPORTER: 1
        TEST_PREFIX: 1
    conan_add_remote:
      pargs:
        nargs: '*'
        flags: []
      kwargs:
        INDEX: 1
        NAME: 1
        URL: 1
    conan_cmake_install:
      pargs:
        nargs: '*'
        flags: []
      kwargs:
        BUILD: +
        INSTALL_FOLDER: 1
        LOCKFILE: 1
        LOCKFILE_NODE_ID: 1
        LOCKFILE_OUT: 1
        PATH_OR_REFERENCE: 1
        REFERENCE: 1
        REMOTE: 1
        ENV: +
        ENV_BUILD: +
        ENV_HOST: +
        GENERATOR: +
        OPTIONS: +
        OPTIONS_BUILD: +
        OPTIONS_HOST: +
        PROFILE: +
        PROFILE_BUILD: +
        PROFILE_HOST: +
        SETTINGS: +
        SETTINGS_BUILD: +
        SETTINGS_HOST: +
    cpmaddpackage:
      pargs:
        nargs: '*'
        flags: []
      spelling: CPMAddPackage
      kwargs: &id001
        DOWNLOAD_COMMAND: 1
        DOWNLOAD_NAME: 1
        DOWNLOAD_NO_EXTRACT: 1
        DOWNLOAD_ONLY: 1
        FIND_PACKAGE_ARGUMENTS: 1
        FORCE: 1
        GITHUB_REPOSITORY: 1
        GITLAB_REPOSITORY: 1
        GIT_REPOSITORY: 1
        GIT_SHALLOW: 1
        GIT_TAG: 1
        HTTP_PASSWORD: 1
        HTTP_USERNAME: 1
        NAME: 1
        NO_CACHE: 1
        SOURCE_DIR: 1
        SVN_REPOSITORY: 1
        SVN_REVISION: 1
        URL: 1
        URL_HASH: 1
        URL_MD5: 1
        VERSION: 1
        OPTIONS: +
    cpmfindpackage:
      pargs:
        nargs: '*'
        flags: []
      spelling: CPMFindPackage
      kwargs: *id001
    cpmdeclarepackage:
      pargs:
        nargs: '*'
        flags: []
      spelling: CPMDeclarePackage
      kwargs: *id001
    packageproject:
      pargs:
        nargs: '*'
        flags: []
      spelling: packageProject
      kwargs:
        BINARY_DIR: 1
        COMPATIBILITY: 1
        DISABLE_VERSION_SUFFIX: 1
        EXPORT_HEADER: 1
        INCLUDE_DESTINATION: 1
        INCLUDE_DIR: 1
        NAME: 1
        NAMESPACE: 1
        VERSION: 1
        VERSION_HEADER: 1
        DEPENDENCIES: +
    cpmusepackagelock:
      pargs: 1
      spelling: CPMUsePackageLock
    cpmregisterpackage:
      pargs: 1
      spelling: CPMRegisterPackage
    cpmgetpackageversion:
      pargs: 2
      spelling: CPMGetPackageVersion
_help_format: Options affecting formatting.
format:
  _help_line_width:
  - How wide to allow formatted cmake files
  line_width: 120
  _help_tab_size:
  - How many spaces to tab for indent
  tab_size: 2
  _help_max_pargs_hwrap:
  - If a positional argument group contains more than this many
  - arguments, then force it to a vertical layout.
  max_pargs_hwrap: 3
  _help_separate_ctrl_name_with_space:
  - If true, separate flow control names from their parentheses
  - with a space
  separate_ctrl_name_with_space: false
  _help_separate_fn_name_with_space:
  - If true, separate function names from parentheses with a
  - space
  separate_fn_name_with_space: false
  _help_dangle_parens:
  - If a statement is wrapped to more than one line, than dangle
  - the closing parenthesis on its own line.
  dangle_parens: false
  _help_line_ending:
  - What style line endings to use in the output.
  line_ending: unix
_help_markup: Options affecting comment reflow and formatting.
markup:
  _help_bullet_char:
  - What character to use for bulleted lists
  bullet_char: '*'
  _help_enum_char:
  - What character to use as punctuation after numerals in an
  - enumerated list
  enum_char: .
  _help_enable_markup:
  - enable comment markup parsing and reflow
  enable_markup: false
