# https://taskfile.dev/#6/installation
version: 3

includes:
  windows: ./Taskfile_windows.yml
  docker: ./docker/Taskfile.yml
  examples: ./examples/Taskfile.yml
  myproj:
    taskfile: ./tests/myproj/Taskfile.yml
    dir: ./tests/myproj
  install:
    taskfile: ./tests/install/Taskfile.yml
    dir: ./tests/install
  minimal:
    taskfile: ./tests/minimal/Taskfile.yml
    dir: ./tests/minimal
  emscripten:
    taskfile: ./tests/emscripten/Taskfile.yml
    dir: ./tests/emscripten
  rpi3:
    taskfile: ./tests/rpi3/Taskfile.yml
    dir: ./tests/rpi3
  rpi4:
    taskfile: ./tests/rpi4/Taskfile.yml
    dir: ./tests/rpi4
  rpi4-vcpkg:
    taskfile: ./tests/rpi4-vcpkg/Taskfile.yml
    dir: ./tests/rpi4-vcpkg
  pico:
    taskfile: ./tests/pico/Taskfile.yml
    dir: ./tests/pico

vars:
  CWD:
    sh: git rev-parse --show-toplevel

tasks:
  ci.test:
    - task: myproj:test
    - task: myproj:test.release
    - task: install

  lint:
    - git ls-files --exclude-standard | grep -E '\.(cpp|hpp|c|cc|cxx|hxx|ixx)$' | xargs clang-format -i -style=file 
    - git ls-files --exclude-standard | grep -E '(CMakeLists\.txt)|(\.(cmake))$' | xargs cmake-format --in-place | xargs cmake-lint --disabled-codes C0103 C0301 R0912 R0915 R0913 --suppress-decorations
    - task: myproj:lint
    - task: install:lint
    - task: minimal:lint
    - task: emscripten:lint
    - task: rpi4-vcpkg:lint
    - npx -y cspell lint --no-progress --show-suggestions

  clean:
    - task: myproj:clean
    - task: install:clean
    - rm -rf {{.CWD}}/install
