# https://taskfile.dev/#6/installation
version: 3

includes:
  windows: ./Taskfile_windows.yml
  docker: ./docker/Taskfile.yml
  examples: ./examples/Taskfile.yml
  myproj:
    taskfile: ./tests/myproj/Taskfile.yml
    dir: ./tests/myproj
  install:
    taskfile: ./tests/install/Taskfile.yml
    dir: ./tests/install
  minimal:
    taskfile: ./tests/minimal/Taskfile.yml
    dir: ./tests/minimal
  emscripten:
    taskfile: ./tests/emscripten/Taskfile.yml
    dir: ./tests/emscripten

vars:
  CWD:
    sh: git rev-parse --show-toplevel

tasks:
  ci:test:
    - task: myproj:test
    - task: myproj:test:release
    - task: install

  lint:
    - git ls-files --exclude-standard | grep -E '\.(cpp|hpp|c|cc|cxx|hxx|ixx)$' | xargs clang-format -i -style=file 
    - git ls-files --exclude-standard | grep -E '(CMakeLists\.txt)|(\.(cmake))$' | xargs cmake-format --in-place | xargs cmake-lint --disabled-codes C0103 C0301 R0912 R0915 R0913 --suppress-decorations
    - task: main:lint
    - task: install:lint
    - task: minimal:lint
    - task: emscripten:lint
    - npx -y cspell lint --no-progress --show-suggestions

  clean:
    - task: main:clean
    - task: install:clean
