# https://taskfile.dev/#/installation
version: 3

tasks:
  test:
    - cmake ./test -B ./test/build -DCMAKE_BUILD_TYPE:STRING=Debug -G "Ninja Multi-Config"
    - cmake --build ./test/build --config Debug
    - cd ./test/build && ctest -C Debug --verbose

  test_release:
    - cmake ./test -B ./test/build -DCMAKE_BUILD_TYPE:STRING=Release -G "Ninja Multi-Config"
    - cmake --build ./test/build --config Release
    - cd ./test/build && ctest -C Release --verbose
    - cmake --install ./test/build

  format:
    - clang-format -i ./test/*.cpp
    - cmake-format --in-place ./Index.cmake ./src/*.cmake

  lint: cmake-lint ./Index.cmake ./src/*.cmake

  clean: 'cd test && {{if eq OS "windows"}} cmd /c "if exist build ( rmdir /s/q build )" {{else}} rm -rf build {{end}}'
