version: 3

tasks:
  gcc:
    - docker-compose up --build build-gcc
    - docker-compose up --build test-gcc
    - docker-compose down

  llvm:
    - docker-compose up --build build-llvm
    - docker-compose up --build test-llvm
    - docker-compose down

  mingw:
    - docker-compose up --build minimal-build-mingw-x64
    - docker-compose up --build minimal-build-mingw-x64-from-env
    - docker-compose up --build minimal-build-mingw-x64-from-triplet
    - docker-compose up --build minimal-build-mingw-x86
    - docker-compose down
    
  emscripten:
    - docker-compose up --build build-emscripten
    - docker-compose down